---
spring: 
  cloud:
    config:
      server: 
        git:
          uri: https://github.com/abhilash28abhi/toll-app-configurations
          search-paths: station*
  security:
    user:
      name: admin
      password: admin
          #search-paths: ConfigData
          #username: usname
          #password: password
          #file:///F:/SpringBoot/toll-app-configurations
          #https://github.com/abhilash28abhi/toll-app-configurations
server:
  port: 8888